version: '3.9'

name: life-vault

services:
  postgres:
    image: postgres:15-alpine
    container_name: life-vault-db
    environment:
      POSTGRES_DB: family_health_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - life_vault
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    container_name: life-vault-backend
    image: ghcr.io/dvary/life-vault-backend:${LIFE_VAULT_VERSION:-latest}
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/family_health_tracker
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 7d
      PORT: 5000
      MAX_FILE_SIZE: 20971520
      UPLOAD_PATH: /app/uploads
      CORS_ORIGIN: https://family.labratindia.org
      TZ: Asia/Kolkata
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - life_vault
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    container_name: life-vault-frontend
    image: ghcr.io/dvary/life-vault-frontend:${LIFE_VAULT_VERSION:-latest}
    environment:
      REACT_APP_API_URL: /api
      TZ: Asia/Kolkata
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - life_vault
    restart: unless-stopped

  nginx:
    container_name: life-vault-nginx
    image: ghcr.io/dvary/life-vault-nginx:${LIFE_VAULT_VERSION:-latest}
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend
    networks:
      - life_vault
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  life_vault:
    driver: bridge
