version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: life-vault-db
    environment:
      POSTGRES_DB: family_health_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - family-health-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: life-vault-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password123}@postgres:5432/family_health_tracker
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      JWT_EXPIRES_IN: 7d
      PORT: 5000
      MAX_FILE_SIZE: 20971520
      UPLOAD_PATH: /app/uploads
      CORS_ORIGIN: ${CORS_ORIGIN:-https://family.labratindia.org}
      TZ: Asia/Kolkata
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Starting backend server...' &&
        npm start
      "
    networks:
      - family-health-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health-check', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-https://family.labratindia.org/api}
    container_name: life-vault-frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-https://family.labratindia.org/api}
      TZ: Asia/Kolkata
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - family-health-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: life-vault-nginx
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend
    networks:
      - family-health-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local

networks:
  family-health-network:
    driver: bridge
